### ISSUE TITLE
Should be upgraded to work with NC 17

### ISSUE THREAD

**Issue by flemmingss** [mamatt/files_readmemd#108]
I see "Server version 26 or lower is required.". This is a very useful app, should be upgraded to support NC 17.

**Comment by Somebodyisnobody** [comment]
Same here

**Comment by flemmingss** [comment]
I tested it, and it works, but it should work "formally" also.

**Comment by Somebodyisnobody** [comment]
@EtHeO18 are you working on this in [EtHeO18/files_readmemd](https://github.com/EtHeO18/files_readmemd)?

**Comment by mlan** [comment]
This issue is really about NC 27, right?

**Comment by Somebodyisnobody** [comment]
> This issue is really about NC 27, right?

Haha, you're right! I just opened the issues sorted by activity and read "Should be upgraded to work with NC <something with 7 at the end>" before commenting...

**Comment by mamatt** [comment]
see #110
