### ISSUE TITLE
Update to NC27

### ISSUE THREAD

**Issue by HappyMan4** [mamatt/files_readmemd#110]
NC27 has been released a while ago, will this app get an update too?

**Comment by jkraffthha** [comment]
Yes please, very useful, please make it NC27 compatible!

**Comment by mmeinesz** [comment]
Hello Mamatt, we are using NC for our company. Your Readmemd is very helpful for us. I would like to donate to you 200EUR for you to update your code to latest version of NC. Also, there are some bugs and features I would like to report. Are you open for this?

**Comment by mamatt** [comment]
Hello, just to clarify a little how this app is developed.

I'm working for Nantes University and I'm developing this app for our Nextcloud instance.

This instance is quite large and we are most of time running NC version N-1, as the time of writing NC26. 

Be sure that is app will be updated to next version of nextcloud, BUT, most of time I will follow entreprise release (at least one month later than public version). Sometime I miss time to update my dev instance  and then this app is not updated until we update our production instance. 

Our next update slot is scheduled around Xmas so expect an update at least 2 week before this.

Hopefully a lot's sooner !

I'll will be directly compatible with NC 28.

Thank you for your patience, as I understand that some of you rely on this app,
but one again even if I only have a few time to update this app, it will be updated.

**Comment by mamatt** [comment]
>. Also, there are some bugs and features I would like to report. Are you open for this?

-> for bugs, open issue and I'll try to fix them.
-> for enhancement, this is totally dependent of my workload ;)

**Comment by Somebodyisnobody** [comment]
What's about providing an update / fix via merge request? Would that be faster if you only need to test?

**Comment by mmeinesz** [comment]
Thanks for your polite answer and greetings to Nantes. I am glad, that the Readme app is constantly developed. 
I don't have a problem to lack behind lateest version of NC, as long as the version is still update in terms of security.

**Comment by jonasgarstick** [comment]
Dear @mamatt, I hope you will find some time to make your app work with NC 27.x.x. We really appreciate your contribution.

**Comment by mamatt** [comment]
I think I have found the issue with markdown module.  
I need to test that everything is ok, and I'll try to publish a new version monday morning !

**Comment by mamatt** [comment]
Release has been published, BUT I had to disable asciidoc engine with this version because of an issue with npm module.
