### ISSUE TITLE
Update to NC28

### ISSUE THREAD

**Issue by ernolf** [mamatt/files_readmemd#124]
It worked on 27 but on 28 it is not even possible to install with force (*`app_install_overwrite`*). 

Please update this great app and don't let it die 🔢 :chart_with_upwards_trend: 

Thanks a lot!
ernolf

**Comment by mamatt** [comment]
NC28 as changed the filelist to vuejs.

I'll need to check deeply what's exactly changed !

**Comment by JSoko** [comment]
https://help.nextcloud.com/t/readme-md-for-nc28/178892

**Comment by mamatt** [comment]
I've read this thread and be sure I'll update the app for NC 28. ( see explanation on #110 )

If everything goes well I'll publish a version for NC27 on monday morning then focus on nc28,
which is vuejs based.

**Comment by zszen** [comment]
> If everything goes well I'll publish a version for NC27 on monday morning

Nice plan

**Comment by simaoafonso-pwt** [comment]
Hi @mamatt, what's the status of this, will you still update to NC 28? Do you have a rough timeline?

**Comment by mamatt** [comment]
We plan to update to NC28 on the first two weeks of august.  
As I won't be available in july, expect a version for the end of June.

**Comment by mamatt** [comment]
just to keep you updated, i've started working on reeadmeMD for NC28.  
As expected there is a lot's of work, the app needs a lot's of rewriting.
Lot's of API were removed and the file app switch to vue.js.

**Comment by mamatt** [comment]
Another quick update.
I'm activly working on the new version.

Most of the app has been re-written to use vue.js
It should be easier to maintain.

Most of things are working but I've reached a nasty bug where  showing a footer file trig a infinite padding-top to the file list.

This make things unusable for now. 

I'll try commit the new code this WE.
You should be able to test it and report me if there are some bugs left.

**Comment by mamatt** [comment]
initial vue.js version has been pushed to v3 branch.
This far from perfect, public view has not been tested yet and there are some CSS bugs.

But fell free to test and give me some feedback !

**Comment by schniepp** [comment]
Hi @mamatt : thanks so much for all your hard work on this!

I just checked out v3.0.0.  I am not a developer, but I am hoping I did it the right way. I didn't use git, just downloaded the zip file from the v3.0.0 branch unpacked it, put it into the NC apps folder, and adjusted permissions. 
When I go into the NC apps manager, it shows correctly "3.0.0"

However, when I browse to a page containing a README.md file, absolutely nothing is rendered on the bottom of the page. I already did a hard page reload via Ctrl-Shift-R (to make sure all apps get a force reload, if that is even necessary). 

What am I missing? What do you mean with private via public views? (Not sure which one I am.) Is a private view one from a user who has full "internal" access to the page? And public (perhaps) a page that can also be seen by users without privileges (or users that are not logged in)?

**Comment by schniepp** [comment]
Thank you so much! It works now!

The README.md and HEADER.md content shows up on the page, with correct markdown rendering. 

One difference I am noticing between v2 and v3 is that in v2, the markdown content shows up for me directly after the files/folder display, where as in v3, it shows up all the way at the bottom of the page. Probably only makes a significant difference on large screens, where the content gets more easily missed when it's at the bottom (especially if it's short so that the page does not fill up. I prefer the way v2 renders it, but it's probably not a dealbreaker for me. I can also run it by my users.

**Comment by mamatt** [comment]
@schniepp this is strange as this is indeed a bug and I'have already solved it !

Can you post screenshot to be sure that this issue is the same

**Comment by mamatt** [comment]
Good news @all 
- public view is now working,
- settings have been updated, they have'nt been migrated to vue.js but this will be for next version
- I might have found a solution to handle the dark mode from OS + light mode from NC
- the code just need somme small cleaning but nothing to fancy
- I'll try to bring back asciidoc engine 

That is to say, release 3.0.0 is now very close \o/

**Comment by mamatt** [comment]
Everything is now working ! 
I'll run extended test and check with NC 29
but expect the new version to be published before the end of the week

**Comment by mamatt** [comment]
New versionhas been published.
I close this isssue.
Please test and open a new issue if any problem.
