### ISSUE TITLE
Readme showing both above and below file list NC27

### ISSUE THREAD

**Issue by sgocken** [mamatt/files_readmemd#127]
We are on NC 27.1
Currently we are seeing:

README
HEADER
File List
README

Is there a setting we are missing that is putting README above the file list as well? Or is README put above if it is smaller than X?

**Comment by mamatt** [comment]
Sound like interval Nextcloud "richspace' is active. 

Disable it and everything should be working as expected.

**Comment by sgocken** [comment]
Here are my current unchanged settings:
![image](https://github.com/mamatt/files_readmemd/assets/607197/00cb5e6b-7ba9-41ee-8793-9635143647d6)

Disable Nextcloud native rich workspaces was already enabled.
Or is this a more global setting?

**Comment by mamatt** [comment]
This seetings is not working very well.
You should disable richworkspace from occ setting.

see https://github.com/nextcloud/text

this settings will be removed in the new version
