### ISSUE TITLE
Version 3.0.0 on Nextcloud 28 no longer provides css selectors based on md file name

### ISSUE THREAD

**Issue by Atn-D** [mamatt/files_readmemd#160]
Thank you very much for this update!

On my instance, I had created custom css based on the names of the md files used by this plug-in.

In the old version, it looked like `.readmemd[data-filename="Bienvenue.md"]{`

By the way, it only worked for the footer, so it would be great to have it back on the footer and added for the header!

**Comment by mamatt** [comment]
You now have .headermd or .footermd class according to the positionnement of the container 

 However, I Can easily add the data file information back in the container !

**Comment by Atn-D** [comment]
@mamatt  I see you've pre-released Aug 19 V3.0.1, when do you expect the release, my association is looking forward to finding the layouts that will enable this feature. :)
