### ISSUE TITLE
NC 25: do not display HEADER.md oder README.md

### ISSUE THREAD

**Issue by mamatt** [mamatt/files_readmemd#78]
In GitLab by @oldsmurf on Oct 26, 2022, 17:26

Nextcloud 25 do not display HEADER.md oder README.md files in files.

**Comment by mamatt** [comment]
I'm actually working on it ;)

**Comment by spreeni151** [comment]
Thank you very much! :-)

**Comment by rasos** [comment]
Works like a charm now on a NC 25.0.5, thanks. I have added `Readme.md` (not capitalized) to make existing native rich workspace descriptions visible again.
